### PR TITLE
Added glsxtrfull from glossaries-extra

### PR DESCRIPTION
**Pull request by JulianGoeltz**
Uses parsing from glossaries file.
Commit includes test coverage.

### CODE REVIEW

**Comment by torik42** [comment]
If I understand correctly, the command adds the full form and abbreviation in parentheses independent of where it is called. Is that correct? Is there any reason, you didn’t add the abbreviation?

**Comment by JulianGoeltz** [comment]
It seems I didn't fully grasp the functions in `glossaries.py` and just looked at the test. Your understanding of the glossaries command is correct, how would one best implement this for YaLafi?

**Comment by torik42** [comment]
Let me first explain what happens in `glossaries.py`. From your fork I assume you know how Macro handler functions work, otherwise read [this](https://github.com/torik42/YaLafi#macro-handler-functions) first. The glossary entries are written to `the_glossary` (the way that works doesn’t matter here). For each command, the macro handler function `f` (line `112` in current master `852f7eb`) is constructed using the two arguments `key` and `mods` in `h_gls` (line `111`). `key` corresponds to the key in `.glsdef`. `get_tokens` (line `113`) get the tokens of the values matching the `key` in `.glsdef`; in line `120` they get expanded; if `mods=[]`, line `121` is irrelevant, o.w. the functions in mods (either `cap_all` or `cap_first`) are applied. Finally, the positions of the new tokens are set to the `\` of the corresponding Macro, e.g. `\gls`. Later, such positions are automatically extended to the full command.

My suggestion would be to first define `\glsxtrshort` and `glsxtrlong` similar how you did it (could you import the necessary functions form glossaries with `from glossaries import …`). These seem to use the `short` and `long` keys. For `\glsxtrfull` one can then add `\newcommand[1]{\glsxtrfull}{\glsxtrshort{#1} (\glsxtrlong{#1})}` assuming this is how it works.

I haven’t properly tested these things and don’t know what exactly I should expect from using the commands, so please check again with running real LaTeX and then add tests with the correct behaviour to `test_glossaries-extra.py`.

**Comment by JulianGoeltz** [comment]
Thanks for this insightful explanation and the suggestion, I think I implemented it, see the new commit. And sorry again for the initial PR, that was full of errors.
I crosschecked the current assumptions in the test with a latex file:
```latex
gls \gls{pp}


glsxtrshort \glsxtrshort{pp}

Glsxtrshort \Glsxtrshort{pp}


glsxtrlong \glsxtrlong{pp}

Glsxtrlong \Glsxtrlong{pp}


glsxtrfull \glsxtrfull{pp}

Glsxtrfull \Glsxtrfull{pp}
```
image
I adapted `tests/test_packages/glossaries-extra.tex` for this, should I commit this as well?

As an aside: the reason why I personally used `\glsxtrfull` is that it does not change the first use flag, i.e. when using `\setabbreviationstyle[acronym]{long-short}` a use of `\gls` after `\glsxtrfull` will still print the long and short version, and I used this in the figures in the paper to have the explanations of acronyms both in the text and captions.

**Comment by torik42** [comment]
Thank you for the contribution, this looks very good now! I would just like to squash them again before merging (or you do so, if you want, see e.g. [here](https://www.internalpointers.com/post/squash-commits-into-one-git)).

> I adapted `tests/test_packages/glossaries-extra.tex` for this, should I commit this as well?

That’s not necessary for now, we also don’t have them in `glossaries.tex`. At some point, I might update `test_glossaries_extra.py` to the new `.glsdef` format. But for now, this is enough.

**Comment by torik42** [comment]
Just one thing. Could you add the new macros to `list-of-macros.md`?

**Comment by JulianGoeltz** [comment]
Added to `list-of-macros.md` and squashed :)

**Comment by JulianGoeltz** [comment]
Oh, sorry. I did look at this but than apparently missed it again. Thanks for spotting!
Added the commas as well

**Comment by torik42** [comment]
Thank you for the nice contribution! Successfully merged into master.

**Pull request merged**
